version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000aart
- name: bob
  coins:
  - 10000token
  - 100000000aart
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000aart
validators:
- name: alice
  bonded: 100000000aart
